name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Hoặc tên nhánh bạn dùng

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.7.3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Tạo ra thư mục ./dist

      - name: Upload build artifact
        uses: actions/upload-artifact@v2  # Sử dụng v2 nếu v3 gặp lỗi
        with:
          name: build-artifact
          path: ./dist  # Đảm bảo thư mục ./dist chứa các tệp đã build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2  # Sử dụng v2 nếu v3 gặp lỗi
        with:
          name: build-artifact  # Tên của artifact khi upload trước đó

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
